/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./../components/layout/BaseLayout.vue')['default']
    IMdiInfomation: typeof import('~icons/mdi/infomation')['default']
    IMdiInformation: typeof import('~icons/mdi/information')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
